services:
  db:
    image: postgis/postgis:16-3.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: safebite
      POSTGRES_USER: safebite
      POSTGRES_PASSWORD: safebite
    volumes:
      - safebite_pg:/var/lib/postgresql/data
volumes:
  safebite_pg:
